### ISSUE TITLE
User story deadline and why so many UI tasks?

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#111]
I thought we had agreed to only focus on user stories until the deadline for adding stories to the sprint backlog. UI and development tasks can mostly wait until that task is done. 

I have been added a few devel and UI tasks, specifically because I'm working on them ATM, so they must be there. But in those exceptional cases I know exactly what I am doing. Also, it is just a temporary measure since we are "cheating", i.e. developing before the sprint backlog has been frozen for the sprint.

But apart from that, can we please go back to focusing only on what needs to be done? What data models need to exist, what views need to exist, how we are going to present information to the user is not important now. The ONLY thing that matter is the user stories, that is the functional requirements of the system.

Right now the issue tracker has become a mess. More so, because many user stories are not even added to the user story project. Some issues which are not user stories are still in the user story project. Since there are so many UI tasks listed as well, it is next to impossible to find anything in the issue tracker anymore. This becomes very frustrating.

Is it possible to quickly fix this? And can we PLEASE put a halt to anything that is not a user story (with the exception of discussions and questions) until we have met the sprint backlog freeze? We really don't have time to focus on UI stuff if we are going to write all the user stories, agree on them and move them into the sprint backlog on time. This should be the focus of all our attention right now.

Remember, we should really only be adding UI and devel tasks AFTER the sprint has kicked off, and when we begin working on implementing stories. Now we are creating implementation tasks that don't even refer to any existing story yet. How is that possible? Can you imagine the hell we are going to go through when we have to link all these UI tasks to the user stories they relate to? That is why I have limited myself to creating implementation tasks for specific user stories and immediately linked them to the story they relate to. I'm not sure how we are best going to be able to achieve this with all the other tasks.

And one final request. Can we try to work less fast and instead focus on doing the right thing? When you write a user story can you just add it right away to the user story project? At least that way, we should be able to go to the project and not have to see all the issues that are irrelevant at this point in time.

**Comment by lcabrini** [comment]
I'm also thinking something else. Maybe we should avoid such a huge queue of stories in one go. Here is an idea:

1. go to User Stories project. 
2. Create any number of user stories as notes.
3. Select one or perhaps a few related stories, convert them to issues
4. Discuss, modify, review and finally propose
5. Upon agreement, move them into product backlog
6. If applicable, propose to move into sprint backlog
7. Select another one or a few user stories, convert to issues
8. Continue like this until all relevant issues are moved out of proposed.

This way we work in a more structured way and the user stories get moved into the backlogs. At the moment there are too many stories with too many issues at the same time. My notification screen is listing very long. I'm having a lot of difficulty finding which issue to adress at a point in time. 

I propose the we should strive to at any point in time have a maximum of 5 or so user stories that have been converted to issues and are still in the proposed queue.

**Comment by BorderITS** [comment]
okay I was thinking those will be needed that's why
