### ISSUE TITLE
As a product manager I want to add a product category

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#112]
### Story 

As a product manager I want to add a product category so that I can organize my products into categories.

### Deps

**Comment by lcabrini** [comment]
I propose that this user story is added to the product backlog.

**Comment by BorderITS** [comment]
agreed

**Comment by lcabrini** [comment]
Now I propose that this is moved to the sprint backlog.

**Comment by BorderITS** [comment]
agreed
