### ISSUE TITLE
As a Product manager I want  add internal ref to my products 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#140]

**Comment by lcabrini** [comment]
Please, please, please stop adding user stories for things that are not functional specs.

A functional spec is "add product", "list products", "delete product" etc. An internal ref is just another field. It does not alter the functionality of the system.

The only way you could use this user story is if there was to be a button "add internal ref" and that linked to a form that allows you to create an internal ref. But, here it is not a functional requirement of the system. It is an attribute of a data model.

**Comment by BorderITS** [comment]
hmm I hear I will remove it
