### ISSUE TITLE
Add product category link is wrong

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#147]
The link to add product category rather goes to add product.

**Comment by BorderITS** [comment]
I also realized that just now

**Comment by lcabrini** [comment]
I have a fix provided but cannot push yet. Hopefully by tomorrow.

**Comment by BorderITS** [comment]
ok

**Comment by lcabrini** [comment]
Did the update fix the issue for you? If so, can we please close this?

**Comment by BorderITS** [comment]
agreed and I'm closing it
