### ISSUE TITLE
Error code when you create product 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#154]
TypeError at /product/add/

%c requires int or char

Request Method: 	POST
Request URL: 	http://localhost:8000/product/add/
Django Version: 	1.10.1
Exception Type: 	TypeError
Exception Value: 	

%c requires int or char

Exception Location: 	/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/contrib/messages/views.py in get_success_message, line 18
Python Executable: 	/home/nelson/Projects/amadaa/ENV/bin/python
Python Version: 	3.4.3
Python Path: 	

['/home/nelson/Projects/amadaa',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages']

Server time: 	Thu, 6 Oct 2016 06:07:41 +0000
Traceback Switch to copy-and-paste view

    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/handlers/exception.py in inner

                    response = get_response(request)

         ...
    ▶ Local vars
    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/handlers/base.py in _get_response

                        response = self.process_exception_by_middleware(e, request)

         ...
    ▶ Local vars
    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/handlers/base.py in _get_response

                        response = wrapped_callback(request, *callback_args, **callback_kwargs)

         ...
    ▶ Local vars
    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/views/generic/base.py in view

                    return self.dispatch(request, *args, **kwargs)

         ...
    ▶ Local vars
    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/views/generic/base.py in dispatch

                return handler(request, *args, **kwargs)

         ...
    ▶ Local vars
    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/views/generic/edit.py in post

                return super(BaseCreateView, self).post(request, *args, **kwargs)

         ...
    ▶ Local vars
    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/views/generic/edit.py in post

                    return self.form_valid(form)

         ...
    ▶ Local vars
    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/contrib/messages/views.py in form_valid

                success_message = self.get_success_message(form.cleaned_data)

         ...
    ▶ Local vars
    /home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/contrib/messages/views.py in get_success_message

                return self.success_message % cleaned_data

         ...
    ▶ Local vars

Request information
USER

admin
GET

No GET data
POST
Variable 	Value
csrfmiddlewaretoken 	

'7rvJN1FbxsaUdA3Lja78iP8ls7hYFmpHhsScELVaEzU9PrekJz48FrSD2mgaDMFu'

internal_ref 	

'opaa'

category 	

'2'

name 	

'amane'

FILES

No FILES data
COOKIES
Variable 	Value
csrftoken 	

'xRK9vNgDQz51nuqwmTcZFNDF1Kvon1aXHS7CmxwCXGPgZlB5Mi9Z2pnXBZuAlrqK'

sessionid 	

'9dkph5glypb4qj4npqgtznl2pwxuxyv2'

META
Variable 	Value
CLUTTER_IM_MODULE 	

'xim'

COLORTERM 	

'gnome-terminal'

CONTENT_LENGTH 	

'124'

CONTENT_TYPE 	

'application/x-www-form-urlencoded'

CSRF_COOKIE 	

'xRK9vNgDQz51nuqwmTcZFNDF1Kvon1aXHS7CmxwCXGPgZlB5Mi9Z2pnXBZuAlrqK'

DBUS_SESSION_BUS_ADDRESS 	

'unix:abstract=/tmp/dbus-mR3TS5TAKu'

DEFAULTS_PATH 	

'/usr/share/gconf/zorin_desktop.default.path'

DESKTOP_SESSION 	

'zorin_desktop'

DISPLAY 	

':0.0'

DJANGO_SETTINGS_MODULE 	

'amadaa.settings'

GATEWAY_INTERFACE 	

'CGI/1.1'

GDMSESSION 	

'zorin_desktop'

GDM_LANG 	

'en_US'

GNOME_DESKTOP_SESSION_ID 	

'this-is-deprecated'

GNOME_KEYRING_CONTROL 	

'/run/user/1000/keyring-jEDFJP'

GNOME_KEYRING_PID 	

'11560'

GPG_AGENT_INFO 	

'/run/user/1000/keyring-jEDFJP/gpg:0:1'

GTK_IM_MODULE 	

'ibus'

GTK_MODULES 	

'overlay-scrollbar:unity-gtk-module'

HOME 	

'/home/nelson'

HTTP_ACCEPT 	

'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'

HTTP_ACCEPT_ENCODING 	

'gzip, deflate'

HTTP_ACCEPT_LANGUAGE 	

'en-US,en;q=0.5'

HTTP_CONNECTION 	

'keep-alive'

HTTP_COOKIE 	

('csrftoken=xRK9vNgDQz51nuqwmTcZFNDF1Kvon1aXHS7CmxwCXGPgZlB5Mi9Z2pnXBZuAlrqK; '
 'sessionid=9dkph5glypb4qj4npqgtznl2pwxuxyv2')

HTTP_HOST 	

'localhost:8000'

HTTP_REFERER 	

'http://localhost:8000/product/add/'

HTTP_UPGRADE_INSECURE_REQUESTS 	

'1'

HTTP_USER_AGENT 	

'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0'

IM_CONFIG_PHASE 	

'1'

INSTANCE 	

''

JOB 	

'dbus'

LANG 	

'en_US.UTF-8'

LANGUAGE 	

'en_US'

LESSCLOSE 	

'/usr/bin/lesspipe %s %s'

LESSOPEN 	

'| /usr/bin/lesspipe %s'

LOGNAME 	

'nelson'

LS_COLORS 	

'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'

MANDATORY_PATH 	

'/usr/share/gconf/zorin_desktop.mandatory.path'

OLDPWD 	

'/home/nelson/Projects'

ORBIT_SOCKETDIR 	

'/tmp/orbit-nelson'

PATH 	

'/home/nelson/Projects/amadaa/ENV/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'

PATH_INFO 	

'/product/add/'

PS1 	

('(ENV) \\[\\e]0;\\u@\\h: '
 '\\w\\a\\]${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\$ ')

PWD 	

'/home/nelson/Projects/amadaa'

QT4_IM_MODULE 	

'xim'

QT_IM_MODULE 	

'ibus'

QT_QPA_PLATFORMTHEME 	

'appmenu-qt5'

QUERY_STRING 	

''

REMOTE_ADDR 	

'127.0.0.1'

REMOTE_HOST 	

''

REQUEST_METHOD 	

'POST'

RUN_MAIN 	

'true'

SCRIPT_NAME 	

''

SELINUX_INIT 	

'YES'

SERVER_NAME 	

'localhost'

SERVER_PORT 	

'8000'

SERVER_PROTOCOL 	

'HTTP/1.1'

SERVER_SOFTWARE 	

'WSGIServer/0.2'

SESSION 	

'zorin_desktop'

SESSIONTYPE 	

'gnome-session'

SESSION_MANAGER 	

'local/Nelson-Zorin-OS9:@/tmp/.ICE-unix/11729,unix/Nelson-Zorin-OS9:/tmp/.ICE-unix/11729'

SHELL 	

'/bin/bash'

SHLVL 	

'1'

SSH_AUTH_SOCK 	

'/run/user/1000/keyring-jEDFJP/ssh'

TERM 	

'xterm'

TEXTDOMAIN 	

'im-config'

TEXTDOMAINDIR 	

'/usr/share/locale/'

TZ 	

'UTC'

UPSTART_SESSION 	

'unix:abstract=/com/ubuntu/upstart-session/1000/11564'

USER 	

'nelson'

VIRTUAL_ENV 	

'/home/nelson/Projects/amadaa/ENV'

VTE_VERSION 	

'3409'

WINDOWID 	

'67108878'

XAUTHORITY 	

'/home/nelson/.Xauthority'

XDG_CONFIG_DIRS 	

'/etc/xdg/xdg-zorin_desktop:/usr/share/upstart/xdg:/etc/xdg'

XDG_CURRENT_DESKTOP 	

'Unity'

XDG_DATA_DIRS 	

'/usr/share/zorin_desktop:/usr/share/gnome:/usr/local/share/:/usr/share/'

XDG_GREETER_DATA_DIR 	

'/var/lib/lightdm-data/nelson'

XDG_MENU_PREFIX 	

'gnome-'

XDG_RUNTIME_DIR 	

'/run/user/1000'

XDG_SEAT 	

'seat0'

XDG_SEAT_PATH 	

'/org/freedesktop/DisplayManager/Seat0'

XDG_SESSION_ID 	

'c2'

XDG_SESSION_PATH 	

'/org/freedesktop/DisplayManager/Session0'

XDG_VTNR 	

'7'

XMODIFIERS 	

'@im=ibus'

_ 	

'./manage.py'

wsgi.errors 	

<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>

wsgi.file_wrapper 	

''

wsgi.input 	

<_io.BufferedReader name=6>

wsgi.multiprocess 	

False

wsgi.multithread 	

True

wsgi.run_once 	

False

wsgi.url_scheme 	

'http'

wsgi.version 	

(1, 0)

Settings
Using settings module amadaa.settings
Setting 	Value
ABSOLUTE_URL_OVERRIDES 	

{}

ADMINS 	

[]

ALLOWED_HOSTS 	

[]

APPEND_SLASH 	

True

AUTHENTICATION_BACKENDS 	

['django.contrib.auth.backends.ModelBackend']

AUTH_PASSWORD_VALIDATORS 	

'********************'

AUTH_USER_MODEL 	

'auth.User'

BASE_DIR 	

'/home/nelson/Projects/amadaa'

CACHES 	

{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

CACHE_MIDDLEWARE_ALIAS 	

'default'

CACHE_MIDDLEWARE_KEY_PREFIX 	

'********************'

CACHE_MIDDLEWARE_SECONDS 	

600

CSRF_COOKIE_AGE 	

31449600

CSRF_COOKIE_DOMAIN 	

None

CSRF_COOKIE_HTTPONLY 	

False

CSRF_COOKIE_NAME 	

'csrftoken'

CSRF_COOKIE_PATH 	

'/'

CSRF_COOKIE_SECURE 	

False

CSRF_FAILURE_VIEW 	

'django.views.csrf.csrf_failure'

CSRF_HEADER_NAME 	

'HTTP_X_CSRFTOKEN'

CSRF_TRUSTED_ORIGINS 	

[]

DATABASES 	

{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': '/home/nelson/Projects/amadaa/db.sqlite3',
             'OPTIONS': {},
             'PASSWORD': '********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': ''}}

DATABASE_ROUTERS 	

[]

DATA_UPLOAD_MAX_MEMORY_SIZE 	

2621440

DATA_UPLOAD_MAX_NUMBER_FIELDS 	

1000

DATETIME_FORMAT 	

'N j, Y, P'

DATETIME_INPUT_FORMATS 	

['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']

DATE_FORMAT 	

'N j, Y'

DATE_INPUT_FORMATS 	

['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']

DEBUG 	

True

DEBUG_PROPAGATE_EXCEPTIONS 	

False

DECIMAL_SEPARATOR 	

'.'

DEFAULT_CHARSET 	

'utf-8'

DEFAULT_CONTENT_TYPE 	

'text/html'

DEFAULT_EXCEPTION_REPORTER_FILTER 	

'django.views.debug.SafeExceptionReporterFilter'

DEFAULT_FILE_STORAGE 	

'django.core.files.storage.FileSystemStorage'

DEFAULT_FROM_EMAIL 	

'webmaster@localhost'

DEFAULT_INDEX_TABLESPACE 	

''

DEFAULT_TABLESPACE 	

''

DISALLOWED_USER_AGENTS 	

[]

EMAIL_BACKEND 	

'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST 	

'localhost'

EMAIL_HOST_PASSWORD 	

'********************'

EMAIL_HOST_USER 	

''

EMAIL_PORT 	

25

EMAIL_SSL_CERTFILE 	

None

EMAIL_SSL_KEYFILE 	

'********************'

EMAIL_SUBJECT_PREFIX 	

'[Django] '

EMAIL_TIMEOUT 	

None

EMAIL_USE_SSL 	

False

EMAIL_USE_TLS 	

False

FILE_CHARSET 	

'utf-8'

FILE_UPLOAD_DIRECTORY_PERMISSIONS 	

None

FILE_UPLOAD_HANDLERS 	

['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']

FILE_UPLOAD_MAX_MEMORY_SIZE 	

2621440

FILE_UPLOAD_PERMISSIONS 	

None

FILE_UPLOAD_TEMP_DIR 	

None

FIRST_DAY_OF_WEEK 	

0

FIXTURE_DIRS 	

[]

FORCE_SCRIPT_NAME 	

None

FORMAT_MODULE_PATH 	

None

IGNORABLE_404_URLS 	

[]

INSTALLED_APPS 	

['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'dashboard',
 'product']

INTERNAL_IPS 	

[]

LANGUAGES 	

[('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]

LANGUAGES_BIDI 	

['he', 'ar', 'fa', 'ur']

LANGUAGE_CODE 	

'en-us'

LANGUAGE_COOKIE_AGE 	

None

LANGUAGE_COOKIE_DOMAIN 	

None

LANGUAGE_COOKIE_NAME 	

'django_language'

LANGUAGE_COOKIE_PATH 	

'/'

LOCALE_PATHS 	

[]

LOGGING 	

{}

LOGGING_CONFIG 	

'logging.config.dictConfig'

LOGIN_REDIRECT_URL 	

'/'

LOGIN_URL 	

'/login/'

LOGOUT_REDIRECT_URL 	

'/login/'

MANAGERS 	

[]

MEDIA_ROOT 	

''

MEDIA_URL 	

''

MESSAGE_STORAGE 	

'django.contrib.messages.storage.fallback.FallbackStorage'

MIDDLEWARE 	

['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

MIDDLEWARE_CLASSES 	

['django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware']

MIGRATION_MODULES 	

{}

MONTH_DAY_FORMAT 	

'F j'

NUMBER_GROUPING 	

0

PASSWORD_HASHERS 	

'********************'

PASSWORD_RESET_TIMEOUT_DAYS 	

'********************'

PREPEND_WWW 	

False

ROOT_URLCONF 	

'amadaa.urls'

SECRET_KEY 	

'********************'

SECURE_BROWSER_XSS_FILTER 	

False

SECURE_CONTENT_TYPE_NOSNIFF 	

False

SECURE_HSTS_INCLUDE_SUBDOMAINS 	

False

SECURE_HSTS_SECONDS 	

0

SECURE_PROXY_SSL_HEADER 	

None

SECURE_REDIRECT_EXEMPT 	

[]

SECURE_SSL_HOST 	

None

SECURE_SSL_REDIRECT 	

False

SERVER_EMAIL 	

'root@localhost'

SESSION_CACHE_ALIAS 	

'default'

SESSION_COOKIE_AGE 	

1209600

SESSION_COOKIE_DOMAIN 	

None

SESSION_COOKIE_HTTPONLY 	

True

SESSION_COOKIE_NAME 	

'sessionid'

SESSION_COOKIE_PATH 	

'/'

SESSION_COOKIE_SECURE 	

False

SESSION_ENGINE 	

'django.contrib.sessions.backends.db'

SESSION_EXPIRE_AT_BROWSER_CLOSE 	

False

SESSION_FILE_PATH 	

None

SESSION_SAVE_EVERY_REQUEST 	

False

SESSION_SERIALIZER 	

'django.contrib.sessions.serializers.JSONSerializer'

SETTINGS_MODULE 	

'amadaa.settings'

SHORT_DATETIME_FORMAT 	

'm/d/Y P'

SHORT_DATE_FORMAT 	

'm/d/Y'

SIGNING_BACKEND 	

'django.core.signing.TimestampSigner'

SILENCED_SYSTEM_CHECKS 	

[]

STATICFILES_DIRS 	

['/home/nelson/Projects/amadaa/static']

STATICFILES_FINDERS 	

['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']

STATICFILES_STORAGE 	

'django.contrib.staticfiles.storage.StaticFilesStorage'

STATIC_ROOT 	

None

STATIC_URL 	

'/static/'

TEMPLATES 	

[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/home/nelson/Projects/amadaa/amadaa/../templates/'],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]

TEST_NON_SERIALIZED_APPS 	

[]

TEST_RUNNER 	

'django.test.runner.DiscoverRunner'

THOUSAND_SEPARATOR 	

','

TIME_FORMAT 	

'P'

TIME_INPUT_FORMATS 	

['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']

TIME_ZONE 	

'UTC'

USE_ETAGS 	

False

USE_I18N 	

True

USE_L10N 	

True

USE_THOUSAND_SEPARATOR 	

False

USE_TZ 	

True

USE_X_FORWARDED_HOST 	

False

USE_X_FORWARDED_PORT 	

False

WSGI_APPLICATION 	

'amadaa.wsgi.application'

X_FRAME_OPTIONS 	

'SAMEORIGIN'

YEAR_MONTH_FORMAT 	

'F Y'

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by lcabrini** [comment]
This should be taken care of now. Please test it.

**Comment by lcabrini** [comment]
If you are no longer getting this error, perhaps we can close this issue?

**Comment by BorderITS** [comment]
ok

**Comment by BorderITS** [comment]
should I close it ?

**Comment by lcabrini** [comment]
yes, please do.
