### ISSUE TITLE
Add type to product

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#156]

**Comment by lcabrini** [comment]
Could you give some more detail as to what the type of the product is. Maybe you could list a few sample product types. Especially I need to understand how to differentiate the product type from the product category.

**Comment by BorderITS** [comment]
like 
Consumable 
service 
stockable product

**Comment by lcabrini** [comment]
OK, so it would work like category right? You get a dropdown where you can select the product type. Is that fine?

**Comment by BorderITS** [comment]
yes that's it
