### ISSUE TITLE
CKEditor integration

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#169]
I have just added CKEditor integration. This has adde a few dependencies, so here are the instructions to get it all working:

1. pip install -r requirements.txt (django-ckeditor is new)
2. ./manage.py collectstatic (this should copy a bunch of files into STATIC_ROOT)
3. download jquery (https://code.jquery.com/jquery-3.1.1.min.js) and place that file in STATIC_ROOT/static/js
4. Start the server, log in, navigate to /product/add/ and hopefully you will have a CKEditor instead of a textarea for description.

The new folder STATIC_ROOT is meant for static files (js, css, etc.) that are not part of our project. The folder is gitignored so nothing you place in it will be committed into git.

Regarding CKEditor, we can do a bunch of customization of what buttons and/or toolbars it displays. That can come later. For now, we are just displaying a default CKEditor.

**Comment by BorderITS** [comment]
CKEditor integration is working fine
