### ISSUE TITLE
User with no permission can still add view and delete unit of mesurement 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#181]

**Comment by lcabrini** [comment]
So they are three different issues, all bugs by the way.

1 User with no permission can add unit of measurement
2. User with no permission can view unit of measurement (not sure that this is a bug)
3.User with no permission can delete unit of measurement

Please create an issue for each action, add Bug to each and then close this.

**Comment by lcabrini** [comment]
Can we close this issue now?

**Comment by BorderITS** [comment]
Yes

**Comment by BorderITS** [comment]
I'm closing it
