### ISSUE TITLE
names of each function are displayed as one word 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#186]

**Comment by BorderITS** [comment]
try to create product or anything and you will see it as one word after finish creating eg productnameeditdelete this how it displays instead of product name edit delete

**Comment by lcabrini** [comment]
Well, it is not really one word. It is rather the fact that there is no spacing between cells. You can see this if you study the page source. But it is still a problem.

**Comment by BorderITS** [comment]
OK I thought it is

**Comment by lcabrini** [comment]
This should be fixed in the latest pull request.
