### ISSUE TITLE
Template errors after latest updates

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#191]
I think we have some unresolved merge conflicts in the files. Moreover, it looks like we have duplication of jquery, bootstrap, etc. We will need to resolve these issues one by one, before it will work.

**Comment by BorderITS** [comment]
Yes I'm experiencing the same thing

**Comment by lcabrini** [comment]
I can do some of it. But we will need to coordinate the efforts if we are going to avoid it getting worse.

**Comment by lcabrini** [comment]
When there are merge conflicts, the merger will have to go in and manually fix them in each file. Otherwise, we will be stuck with non-functional code.

**Comment by BorderITS** [comment]
Yes I'm experiencing the same thing  and i cant even start the server

**Comment by lcabrini** [comment]
I tried reverting but it has made things worse. Now the files in my latest pull request are gone for some reason. And I cannot send a new pull request because I am told I am behind upstream. 

I think I have to resort to git reset --hard now. That works locally, but now I try to push and it says my local is behind....

**Comment by lcabrini** [comment]
OK, I did the following:

1. git reset --hard <commit sha of last good commit>
2. git push --force

All this is a really bad idea. Don't know what had happened that screwed the last two commits up so bad. 

Can we all make an effort to avoid this happening again? It really takes up a lot of time having to do this type of housecleaning exercise.

**Comment by lexenington** [comment]
So Lorenzo if I get you well you are saying that we should avoid 
git reset --hard
git push --force

I  had some trouble since sunday evening as my codes did not work well. I deleted m files and did a fresh git pull from master. Hope that is not an issue. I had scrap all that i was doing before so i could start afresh

**Comment by lcabrini** [comment]
The problem is fixed now. Going forward we have to be more careful and only send pull requests when we have done adequate local testing. 

If something is not working, please let me know so that we try to resolve everything.

**Comment by BorderITS** [comment]
Yes we should try to make sure that it is really working well on our local system before we push it to the remote if not we will not move forward
