### ISSUE TITLE
Amadaa app runs slow when there's no internet 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#194]

**Comment by lcabrini** [comment]
I think have figured out what it is. If you don't specify the URL to bootstrap in the settings file, django-bootstrap3 will assume that you will load it from the Net. Great if you have really good Internet, less great if your Net is flaky.

Will work on fixing this.

**Comment by lcabrini** [comment]
I've uploaded a possilbe fix. Could you please try it.

**Comment by BorderITS** [comment]
ok

**Comment by lcabrini** [comment]
So what was the outcome, is it faster or not? By the way you will need to download the bootstrap package and put it in STATIC_ROOT/static.

**Comment by BorderITS** [comment]
where's the link to get this

**Comment by lcabrini** [comment]
https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip

**Comment by lcabrini** [comment]
Has this issue been resolved yet?

**Comment by BorderITS** [comment]
Yes and I'm closing this issue
