### ISSUE TITLE
Add and delete buttons not working 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#201]

**Comment by BorderITS** [comment]
not working on all the apps

**Comment by lcabrini** [comment]
A little more detail would be helpful. It works here.

**Comment by lcabrini** [comment]
Actually you are right. Don't know what happened. Maybe the URL to bootstrap is wrong or something. Looking into it.

**Comment by lcabrini** [comment]
Strange. It works on/off.
