### ISSUE TITLE
New header

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#206]
SirMac has added a new header. Thank you for that work. I think it look much better now. A few things come to mind:
1. when the product app is done, 'No company' should be replaced by actual company name. But we can't do anything about that.
2. On the product pages, there is now a gap between the header and the menu, which does not look good. But I think I made a mistake and put the message area BEFORE the nav area. Will fix that.

Apart from that, any other comments will be helpful.

**Comment by lcabrini** [comment]
I just did a pull request that places the message area below the nav.

**Comment by BorderITS** [comment]
Page header should be static

**Comment by lcabrini** [comment]
The gap between header and menu is now gone. Good work, @SirMac

**Comment by SirMac** [comment]
welcome
