### ISSUE TITLE
Possible reason to upgrade django

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#215]
For pricing I would like to use a specialized field type. This is provided by this project: https://github.com/django-money/django-money

There is even an add-on for it to support currency exchange, if we should need that later. However, this does not work with django 1.10.1 (the version we are using), as can been seen from this issue: https://github.com/django-money/django-money/issues/222

It turns out that it is cause by an upstream bug, namely: https://code.djangoproject.com/ticket/27220

The solution seems to be to either downgrade to 1.10 or to upgrade to 1.10.2. Since 1.10.x are bugfixes on top of 1.10, upgrade seems a better path than downgrading.

Can we decide on this since I need this in order to move on?

**Comment by lcabrini** [comment]
I did a test upgrade in a branch and the upgrade seems to work fine. Of course, I haven't done any extensive testing. Still, if it allows us to use the django-money app, I think it will be worth it.

**Comment by BorderITS** [comment]
Yes you can to  me

**Comment by lcabrini** [comment]
OK, going ahead.

**Comment by BorderITS** [comment]
alright
