### ISSUE TITLE
The Amadaa header

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#223]
@lexenington and I had this conversation a few weeks ago. We were thinking of creating a top bar with a user menu, containing functions such as logout, notifications, etc. The idea was to make the top bar the only fixed item on the page. We would make it very thin so as not to eat too much screen real estate.

Now that I see our header, I'm evolving that thought a little. Since we developing an application and not a website, excessive branding should not be so necessary. Couldn't we merge the header and the top bar. The current header could become a little bit smaller (50-60% of its current height) and be made fixed on the pages. The header might not need to show up at all on the login page.

We wouldn't need Amadaa on this bar. Instead we could make i small logo area plus the company name to the left. The logo area would allow an organization to upload their logo. To the right, where we at the moment have the company name, about and logout/login, we could just have two icons, one for notifications and one the drops down the user menu. The user menu would contain logout plus some other items.

**Comment by BorderITS** [comment]
That's not bad too

**Comment by lcabrini** [comment]
Pulling @SirMac and @lexenington  into this discussion. What do you guys think?

**Comment by SirMac** [comment]
Having a smaller header will be ok but  instead of merging the top bar into the header, we can take it off leaving the buttons there.

**Comment by lcabrini** [comment]
Ok, let's give it a try.
