### ISSUE TITLE
The Amadaa footer

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#224]
I like the new Amadaa footer. It looks more consistent than the previous one.

When I think of it though, I don't think it needs to be fixed. There are two main reasons:
1. The footer will later contain more information
2. The header/top bar will become fixed as it contains a way to get to personal info quicky

With regards to (1), eventually the footer is going to contain a message "powered by amadaa", which will link to a static page with information about the projects. All of you will have your names there as contributors. Then there will be a supported by X, where X is the name of somebody or some organization that provides support for amadaa. With these new items in place the footer will become larger, and would thus eat up too much space on the screen.

With regards to (2), you can follow my ideas here #223 where I discuss my ideas about the amadaa header.

**Comment by lcabrini** [comment]
Pulling in @SirMac  into the discussion and @lexenington into the discussion for your opinions.

**Comment by SirMac** [comment]
This same idea occur to me and I was planning to change the fixed footer.

**Comment by lcabrini** [comment]
ok cool.
