### ISSUE TITLE
Mess up in merge conflict resolution.

### ISSUE THREAD

**Issue by lcabrini** [borderitsolutions/amadaa#228]
@SirMac I think I messed up a bit when I was trying to resolve a merge conflict. As a result, the menu is now gone, replace by a bullet list. Would you be able to fix this?

**Comment by lcabrini** [comment]
Actually, I'm studying the output from view source, and I'm not sure this was done by the merge conflict resolution. I think we have a DIV within a UL. Not sure that is correct.

**Comment by SirMac** [comment]
I will check it.

**Comment by BorderITS** [comment]
this working I'm closing this isuue
