### ISSUE TITLE
runserver not working

### ISSUE THREAD

**Issue by SirMac** [borderitsolutions/amadaa#295]
After a pull from upstream master, runserver gives an error as shown below.
![runserver error2](https://cloud.githubusercontent.com/assets/22539549/20886175/ac9eb7b8-baec-11e6-999d-eb1248fde77e.png)

**Comment by BorderITS** [comment]
Me too still not qor

**Comment by lcabrini** [comment]
It is simple. In python 2, a print command could look like this:

`print "hello"`

But in python 3, print is a proper function, so it must be:

`print("hello")`

The solution to add parenthesis to the print call.

**Comment by BorderITS** [comment]
hmmm can you help fix this

**Comment by poeticabdul** [comment]
Have sent a pull request removing the print statements. After a merge, your issues should be fixed

**Comment by BorderITS** [comment]
yes i have seen it and Lorenzo also fixed the print issues now i want to merge your pull request but it says conflict and i dont know what to do now

**Comment by poeticabdul** [comment]
Did anyone send a pull request before me?

**Comment by BorderITS** [comment]
yes Lorenzo

**Comment by BorderITS** [comment]
solformset = SOLFormSet(request.POST, request.FILES)
 
         if soform.is_valid():
-            print "soform is valid"
+            print("soform is valid")
             sales_order = soform.save(commit=False)
-            print sales_order
+            print(sales_order)
             solformset = SOLFormSet(request.POST, request.FILES, instance=sales_order)
 
             if solformset.is_valid():
-                print "solformset is valid"
+                print("solformset is valid")
 
         return HttpResponse("tested well?")
 
@@ -116,4 +116,4 @@ def post(self, request, *args, **kwargs):
             return HttpResponseRedirect(url)
         else:
             messages.success(self.request, self.success_message)
-            return super(SalesOrderDelete, self).delete(request, *args, **kwargs)
+            return super(SalesOrderDelete, self).delete(request, *args, **kwargs)

**Comment by BorderITS** [comment]
check the close pull request u will see it there

**Comment by poeticabdul** [comment]
Cool, hold on and let me fix this

**Comment by BorderITS** [comment]
ok Sir

**Comment by BorderITS** [comment]
![code](https://cloud.githubusercontent.com/assets/20581281/20919848/95321a0a-bb52-11e6-98a0-bb7e7b3825a1.png)

**Comment by poeticabdul** [comment]
run the migrations on the sales app and then add some prices to the pricelist model.

Can you now merge?

**Comment by BorderITS** [comment]
ok

**Comment by BorderITS** [comment]
Still same problem i don't know why mine  isn't working

**Comment by poeticabdul** [comment]
Maybe @lcabrini can help? He understands the django-money app more than me.

**Comment by BorderITS** [comment]
Ok then I will contact him for support......... Thanks Man

**Comment by poeticabdul** [comment]
Hope your issue is fixed now? @BorderITS

**Comment by BorderITS** [comment]
Yes but when i clicked on view person details it gives error and i also don't see unit price, uom, discount in the sales order app

**Comment by poeticabdul** [comment]
The error you see when you click person is because there's no template (html) for it. Not anything serious.

There's unit price, what is not available is uom and discount because these are not present in Odoo. It can be added anytime though.

**Comment by BorderITS** [comment]
then we will need it thanks man I'll look for my unit price
