### ISSUE TITLE
As a user i want to log in

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa#5]
### Story

As a user I want to log in so that I can use amadaa.

### Deps

* [ ] #2 UI
* [ ] #62 View
* [ ] #63 Model

**Comment by lcabrini** [comment]
I propose that this story is added to the product backlog.

**Comment by BorderITS** [comment]
agreed

**Comment by lcabrini** [comment]
I will now propose that this goes into the sprint backlog. I have two reaons for this:

1. it is needed by *everything* else
2. I have cheated a bit and already started coding on this.

**Comment by lcabrini** [comment]
@BorderITS ping. Can you please agree to my proposal of adding this to sprint backlog. That way we get our first sprint backlog story. (we need to add many more)

**Comment by BorderITS** [comment]
Agreed

**Comment by lcabrini** [comment]
OK, I'm going right ahead with implementing.

**Comment by BorderITS** [comment]
Ok

**Comment by BorderITS** [comment]
a user can now login into Amadaa

**Comment by BorderITS** [comment]
i propose we move it to testing

**Comment by lcabrini** [comment]
Moved. I'm doing this based on the idea that the story is functionally complete.

**Comment by BorderITS** [comment]
ok then

**Comment by lcabrini** [comment]
How far have we come in testing this. Is there anything functionally missing that prevents us from moving it to complete (at least for this sprint). Even if the login form might not look like we want it to (I don't know if this is the case), that is just a look aspect. If login works, can we move to completed?

**Comment by BorderITS** [comment]
Yes and I'm closing this issue
